config/routes.rb
Rmys::Application.routes.draw do
  

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "home/index"

  devise_for :users, :controllers => {:sessions => "sessions"}

  root to: "home#index"

  resources :challenges, only: [:create, :index, :new]
  resources :genres, only: :index
  resources :artists, only: :index
  resources :songs, only: :index
  resources :users, only: [:show, :update]
  resources :fan_musicians, only: :create
  resources :validations, only: [:create, :show, :index]
  resources :payments, only: [:new, :create]  

  resources :musician_profiles do 
    resources :tips, only: [:new, :create]
  end

  resources :concerts, only: [:show, :new, :create, :destroy] do 
    resources :tickets, only: [:new, :create]
    resource :broadcast, only: :show, controller: "broadcast"
  end  

  
  

end

app/models/musician_profile.rb
require './lib/name_helper.rb'
class MusicianProfile < ActiveRecord::Base
  extend NameHelpers::SearchMethods
  include Rails.application.routes.url_helpers
  attr_accessible :edito, :other_url, :name, :photo, :youtube_url, :user_id, :validation, :photo_cache, :remove_photo, :facebook_url

  belongs_to :user

  has_many :concerts, dependent: :destroy
  has_many :fan_musicians, dependent: :destroy, foreign_key: 'musician_id'
  has_many :fans, through: :fan_musicians
  has_one :pending_musician_validation, dependent: :destroy
  has_many :tips
  has_one :balance, class_name: 'MusicianBalance', dependent: :destroy

  validates :edito, :length => { :maximum => 300, :too_long => "Description is too long, %{count} characters is the maximum allowed" }
  validates_presence_of :user_id, :name
  validates_uniqueness_of :user_id

  validates :youtube_url, format: {with: /(^$|youtube\.com\/watch\?v=.+)/, message: 'invalid, must be a youtube url'}, allow_blank: true
  validates :youtube_url, format: {with: URI::regexp(%w(http https)), message: 'insert the entire url including http'}, allow_blank: true 
  validates :facebook_url, format: {with: /(^$|facebook\.com\/.+)/, message: 'invalid, must be a facebook url'}, allow_blank: true
  validates :facebook_url, format: {with: URI::regexp(%w(http https)), message: 'insert the entire url including http'}, allow_blank: true


  validates :other_url, format: {with: URI::regexp(%w(http https)), message: 'insert the entire url including http'}, allow_blank: true



  mount_uploader :photo, PhotoUploader

  before_create :build_pending_validation, :build_default_balance

  delegate :credit, to: :balance, prefix: true

  scope :valid, where(validation: true)

  def to_s
    name
  end

  def can_play_concert?
    concerts.non_performed.count < 1    
  end

  def has_fan?(user)
    fans.exists?(user)
  end

  def increase_credit(credit)
    balance.credit += credit
    balance.save
  end

  def valid_profile?
    validation
  end

  alias :is_valid? :valid_profile?

  def domain_for_other_url
    URI.parse(other_url).host.gsub(/.*www\./i,'')
  end

  def valid_concerts
    concerts.non_performed.valid_date
  end

  def non_performed_concerts
    concerts.non_performed
  end

  private
  def build_pending_validation
    build_pending_musician_validation
    true
  end

  def build_default_balance
    build_balance
    true
  end


end

app/controllers/musician_profiles_controller.rb
class MusicianProfilesController < ApplicationController
  protect_from_forgery
  before_filter :get_musician_profile, except: [:new, :create, :index]
  before_filter :authenticate_user!, except: [:show, :index]

  def index
    @musicians = get_profiles
    respond_to do |format|
      format.html 
      format.json { render json: @musicians}
    end
  end

  def show
    @is_same_user = is_same_user?
    @concerts = @musician_profile.non_performed_concerts
    if user_signed_in?
      @url = session[:first_url] || request.env["HTTP_REFERER"] || musician_profile_path(@musician_profile)
      @tip = Tip.new(user_id: current_user.id, musician_profile_id: @musician_profile.id) 
    end
  end

  def new
    @musician_profile = MusicianProfile.new
    @musician_profile.user = current_user
    respond_to do |format|
      format.html
    end
  end

  def edit
    unless @musician_profile
      render action: "new"
    end
  end

  def create
    if @musician_profile = MusicianProfile.create(params[:musician_profile].merge(user_id: current_user.id))
      redirect_to(@musician_profile)
    else
      if current_user.musician_profile
        flash[:error] = 'You already have a Profile.'
        redirect_to musician_profile_path(current_user.musician_profile)
      else
        render action: "new"
      end
    end
  end


  def update
    respond_to do |format|
      if is_same_user?
        if @musician_profile.update_attributes(params[:musician_profile])
          format.html { redirect_to musician_profile_path(current_user.musician_profile), notice: 'Profile updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @musician_profile.errors, status: :unprocessable_entity }
        end
      else
          flash[:error] = 'You can\'t edit another\'s person profile'
          if current_user.musician_profile
            format.html { redirect_to edit_musician_profile_path(current_user.musician_profile) }
          else
            format.html { redirect_to new_musician_profile_path }
          end
          format.json { render json: @musician_profile.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @musician_profile.destroy if @musician_profile == current_user.musician_profile
    redirect_to root_url
  end

  private
  def get_musician_profile
    @musician_profile = MusicianProfile.find(params[:id])
  end

  def is_same_user?
    user_signed_in? && @musician_profile == current_user.musician_profile
  end

  def get_profiles_from_search(search)
    MusicianProfile.find_by_name_like(search).valid
  end

  def get_profiles
    params.key?(:name) ? get_profiles_from_search(params[:name]) : MusicianProfile.all
  end
end

app/helpers/musician_profiles_helper.rb
module MusicianProfilesHelper
  def other_url_tag(asset)
    tag = asset
    tag = image_tag("#{asset}.png") if Rails.application.assets.find_asset("#{asset}.png")
    tag
  end

  def add_fb_like
    "<fb:like send='true' width='450' show_faces='true' colorscheme='dark'></fb:like>".html_safe
  end
end

app/views/musician_profiles/_concert.html.erb
<div class="row-fluid">
  <div class="span12 well-inverse concert-area" data-role="concert-description">
    <div class="row-fluid">
      <div class="span8 offset2 text-center">
        <% if @is_same_user %>
        <div class="row-fluid">
          <%= link_to 'GO LIVE', '#', class: 'btn btn-rmys' %>
        </div>
        <br/>
        <% end %>
        <h4 class="row-fluid">
          Concert
        </h4>

      </div>             
      <div class="span2">
        <div class="row-fluid">
          <%= link_to("Cancel", concert_path(concert), method: :delete, :class => "btn btn-primary") if @is_same_user %>
        </div>
      </div>
    </div>
    <br/>
    <div class="row-fluid text-center">
      <div class="span4">Name: <%= concert.name %></div>
      <div class="span4">Date: <%= concert.pretty_date %></div>
      <div class="span4">Duration: <%= concert.duration %> minutes</div>
    </div>
    <br/> 
    <div class="row-fluid text-center">
      <div class="span4">Artist: <%= concert.challenge.artist_name %></div>
      <div class="span4">Song: <%= concert.challenge.song_name %></div>
      <div class="span4">Genre: <%= concert.genres %></div>
    </div>
    <br/> 
    <div class="row-fluid text-center">
      <%= concert.description %>
    </div>    
  </div>
</div>

app/views/musician_profiles/_profile_form.html.erb
<div class="well container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="thumbnails">
        <li class="span8">
          <% if @musician_profile.photo? %>
            <%= image_tag @musician_profile.photo_url.to_s %>
          <% else %>
            <img data-src="holder.js/200x200" alt="">
          <% end %>
        </li>         
      </ul>
    </div>

    <div class="span6">
      <%= simple_form_for @musician_profile do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, :input_html => {:onchange => 'readURL(this)'}, label: 'Picture',label_html: {:class => 'btn', id: 'musician_profile_photo_btn'} %>
        <%= f.input :edito, as: :text,label: 'Description' %>
        <%= f.input :youtube_url %>
        <%= f.input :facebook_url %>
        <%= f.input :other_url %>
        <%= f.button :submit, :class => 'btn btn-rmys' %>
      <% end %>     
    </div>
  </div>

</div>

app/views/musician_profiles/edit.html.erb
<%= render partial: 'profile_form' %>

app/views/musician_profiles/index.html.erb
<% @users.each do |user| %>
  <div><%= link_to user.name, user %></div>
<% end %>

app/views/musician_profiles/new.html.erb
<%= render partial: 'profile_form' %>

app/views/musician_profiles/show.html.erb
<% if @is_same_user %>
<div class="row-fluid">
  <div class="span2 offset5 text-center">
    <% if @musician_profile.can_play_concert? %>
      <%= link_to "Play a Challenge", challenges_path, :class => "btn btn-rmys" %>
    <% end %>
  </div>
  <div class="span1 offset4">
    <%= link_to 'Edit', edit_musician_profile_path(@musician_profile), class: 'btn pull-right' %>
  </div>
</div>
<% end %>

<br/>
<div class="well container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <ul class="thumbnails">
        <li class="span10">
          <% if @musician_profile.photo? %>
            <%= image_tag @musician_profile.photo_url.to_s %>
          <% else %>
            <img data-src="holder.js/200x200" alt="">
          <% end %>
        </li>
        <% if @is_same_user %>
          <%= form_for @musician_profile, :html => {:multipart => true, :class => 'photo_form'} do |f| %>
            <p>
              <%= f.file_field :photo %>
              <%= f.submit %>
            </p>
          <% end %>
        
          <li class="span2">
          <a id="musician_profile_photo_btn" class="btn">
            Picture
          </a>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="span8">
      <h3 class="text-center"><%= @musician_profile.name %></h3>

      <% unless @concerts.empty? %>
        <% @concerts.each do |concert| %>
          <%= render partial: 'concert', object: concert %>
        <% end %>
      <% end %>

      <br/>
      <br/>

      <div class="row-fluid">
        <%= @musician_profile.edito %>
      </div>




    </div>
    <div class="span2">
      <% if @is_same_user %>
        <div class="row-fluid text-right">
          <strong>Balance:</strong> <%= pluralize @musician_profile.balance_credit, 'credit' %>
        </div>
        <br/>
      <% elsif user_signed_in? %>
        <div class="row-fluid">
          <%= link_to 'TIP this Musician','#give-tip-modal', data: {toggle: 'modal'} ,:class => 'btn btn-rmys pull-right' %>
        </div>
        <%= render @tip %>
        <br/>
        <% unless @musician_profile.has_fan?(current_user)%>
          <div class="row-fluid">
            <%= link_to "Become Fan", fan_musicians_path(id: @musician_profile.id), method: :post, :class => "btn pull-right"%>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>



  <br/>

  <div class="row-fluid">
    <ul class="no-list">
      <% if @musician_profile.youtube_url.present? %>
        <li class="horizontal"><a id="youtube-url" target="_blank" href="<%= @musician_profile.youtube_url %>"><%= image_tag 'youtube.com.png' %></a></li>
      <% end %>
      <% if @musician_profile.facebook_url.present? %>
        <li class="horizontal"><a id="facebook-url" target="_blank" href="<%= @musician_profile.facebook_url %>"><%= image_tag 'facebook.com.png' %></a></li>
      <% end %>
      <% if @musician_profile.other_url.present? %>
        <li class="horizontal"><a id="other-url" target="_blank" href="<%= @musician_profile.other_url %>"><%= other_url_tag @musician_profile.domain_for_other_url %></a></li>
      <% end %>
    </ul>
  </div>
  <br />

  <div class="row-fluid">
    <%= add_fb_like %>
  </div>

  <hr class="soften"/> 

</div>