config/routes.rb
Rmys::Application.routes.draw do
  

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "home/index"

  devise_for :users, :controllers => {:sessions => "sessions"}

  root to: "home#index"

  resources :challenges, only: [:create, :index, :new]
  resources :genres, only: :index
  resources :artists, only: :index
  resources :songs, only: :index
  resources :users, only: [:show, :update]
  resources :fan_musicians, only: :create
  resources :validations, only: [:create, :show, :index]
  resources :payments, only: [:new, :create]  

  resources :musician_profiles do 
    resources :tips, only: [:new, :create]
  end

  resources :concerts, only: [:show, :new, :create, :destroy] do 
    resources :tickets, only: [:new, :create]
    resource :broadcast, only: :show, controller: "broadcast"
  end  

  
  

end

app/models/user.rb
require './lib/name_helper.rb'
class User < ActiveRecord::Base
  extend NameHelpers::SearchMethods
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :photo, :photo_cache, :remove_photo
  # attr_accessible :title, :body
  validates_uniqueness_of :email
  validates_presence_of :email, :name

  has_one :musician_profile, dependent: :destroy
  has_many :challenges, dependent: :destroy
  has_many :fan_musicians, dependent: :destroy, foreign_key: 'fan_id'
  has_many :musicians, through: :fan_musicians
  has_one :balance, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :concerts, through: :tickets, :uniq => true
  has_many :tips
  has_many :payments

  mount_uploader :photo, PhotoUploader

  before_create :build_default_balance

  delegate :credit, to: :balance, prefix: true

  def is_musician?
    musician_profile.present? && musician_profile.is_valid?
  end

  def wallet
    unless @wallet
      musician = musician_profile
      if musician
        @wallet = Wallet.new(balance, musician.balance)
      else
        @wallet = balance
      end
    end
    @wallet
  end


  def has_ticket?(concert)
    concerts.include?(concert) || is_musician? && musician_profile.concerts.include?(concert)
  end

  def has_credit? 
    wallet.credit > 0
  end

  def has_enough_credit?(price = 10)
    wallet.credit >= price.to_i
  end

  def reduce_credit(amount = 10)
    wallet.reduce_credit(amount)
  end

  def increase_credit(amount = 10)
    balance.increase_credit(amount)
  end

  private
  def build_default_balance
    build_balance
    true
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_user
  before_filter :same_user?, only: :update

  def show
    @is_same_user = current_user == @user
    @challenges = @user.challenges.includes(:concerts => :musician_profile).includes(:song => :artist)
    @concerts_challenged = @challenges.inject([]) do |result, challenge|
      result << challenge.concerts.last if challenge.concerts.any?
      result
    end
    @concerts_payed = @user.concerts.non_performed.closest.greater_date.limit(5).includes(challenge: {song: :artist})
    @musicians = @user.musicians
  end

  def update
    respond_to do |format|
    @user = User.find(params[:id])
      if @user.update_attributes params[:user]
        format.html { redirect_to user_path(@user), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def same_user?
    unless current_user == @user
      flash[:error] = "You can only visit your profile"
      redirect_to :back # halts request cycle
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def show_musician_name
    if user_signed_in?
      if current_user.is_musician?
        current_user.musician_profile.name
      else
        current_user.name
      end
    end
  end
  
end

app/views/users/show.html.erb
<div class="well container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <ul class="thumbnails">
        <li class="span8">
          <% if @user.photo? %>
            <%= image_tag @user.photo_url %>
          <% else %>
            <img data-src="holder.js/200x200" alt="">
          <% end %>
        </li>
        <% if @is_same_user %>
          <%= form_for @user, :html => {:multipart => true, :class => 'photo_form'} do |f| %>
            <p>
              <%= f.file_field :photo %>
              <%= f.submit %>
            </p>
          <% end %>
        
          <!-- <input id="musician_profile_photo" name="musician_profile[photo]" type="file"> -->
          <a id="user_photo_btn" class="btn">
            Picture
          </a>
        <% end %>
      </ul>
    </div>
    <div class="span6 text-center">
      <h3><%= @user.name %></h3>
    </div>
    <div class="span3 subpattern3">
      <div class="row-fluid text-right">
        <strong>Balance:</strong> <%= pluralize @user.balance.credit, 'credit' %>
      </div>
      <br/>
      <div class="row-fluid">
        <%= link_to 'Buy Credits', new_payment_path, :class => 'btn pull-right', remote: true %>
      </div>
    </div>
  </div>
  <br/>
  <% if @concerts_payed.any? %>
    <div class="row-fluid">
      <h4 class="span3">
        You've tickets for:
      </h4>
      <div class="span4">
        <table class="table subpattern5">
          <% @concerts_payed.each do |concert| %>            
            <tr>
              <td><%= link_to concert.name, concert_path(concert) %></td>
              <td><%= concert.artist %></td>
              <td><%= concert.song %></td>
              <td><%= concert.pretty_date %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>

  <br/>
  <% unless @challenges.empty? %>
    <div class="row-fluid subpattern5">
        <div class="span5">
          <div class="row-fluid">
            <h4>Challenge Sent:</h4>
          </div>
          <% @challenges.each do |challenge| %>
            <div class="row-fluid">
              <div><%= "Artist: #{challenge.artist_name}, Song: #{challenge.song_name}, Genre: #{challenge.genres_list}" %></div>
            </div>
          <% end %>
        </div>
        <% if @concerts_challenged.any? %>
          <div class="span5">
            <div class="row-fluid">
              <h4>Next Concert:</h4>
            </div>
            <% @concerts_challenged.each do |concert| %>
              <div class="row-fluid">
                <%= "Challenge raised by: #{concert.musician_profile.name}, Date: #{concert.pretty_date}" %>
              </div>
            <% end %>
          </div>
        <% end %>
    </div>
  <% end %>

  <% if @musicians.any? %>
    <div class="row-fluid">
      <h4 class="span3">
        Fan of:
      </h4>
      <div class="span4">
        <table class="table subpattern5">
          <% @musicians.each do |musician| %>
          <tr>
            <td><%= link_to musician, musician_profile_path(musician) %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
</div>