config/routes.rb
Rmys::Application.routes.draw do
  

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "home/index"

  devise_for :users, :controllers => {:sessions => "sessions"}

  root to: "home#index"

  resources :challenges, only: [:create, :index, :new]
  resources :genres, only: :index
  resources :artists, only: :index
  resources :songs, only: :index
  resources :users, only: [:show, :update]
  resources :fan_musicians, only: :create
  resources :validations, only: [:create, :show, :index]
  resources :payments, only: [:new, :create]  

  resources :musician_profiles do 
    resources :tips, only: [:new, :create]
  end

  resources :concerts, only: [:show, :new, :create, :destroy] do 
    resources :tickets, only: [:new, :create]
    resource :broadcast, only: :show, controller: "broadcast"
  end  

  
  

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  attr_accessible :challenge_id, :date, :description, :name, :performed, :ticket_price, :musician_profile_id, :duration, :end_date

  belongs_to :challenge
  belongs_to :musician_profile

  has_many :tickets, dependent: :destroy
  has_many :users, through: :tickets

  validates_presence_of :date, :name, :musician_profile, :challenge, :duration
  validates_numericality_of :duration

  validates :description, :length => { :maximum => 300 }

  validates :musician_profile_id, uniqueness: {scope: :performed, message: "already have one concert to be performed", unless: lambda{|concert| concert.performed} }
  validate :duration, :inclusion => { :in => [10, 30], :message => "%{value} is not a valid duration" }
  # validate :musician_has_more_than_one_non_performed_concert
  validate :date_is_less_than_now, on: :create

  scope :non_performed, where(performed: false)
  scope :recent, order('id desc')
  scope :greater_date, lambda { |datetime = DateTime.now| where("date > ?" , datetime) }
  scope :less_date, lambda { |datetime = DateTime.now| where("date < ?", datetime)}
  scope :closest, order('date asc')
  scope :valid_date, lambda {where("end_date > ?", DateTime.now)}

  delegate :song, :artist, to: :challenge
  delegate :balance, to: :musician_profile, :prefix => :musician

  before_save do
    self.end_date =  self.date + self.duration.minutes
  end

  alias :musician :musician_profile

  def pretty_date
    date.strftime("%d/%m/%Y %I:%M%p")
  end


  class << self
    def closest_concert
      valid_date.non_performed.closest.first
    end

    def farest_concert
      valid_date.non_performed.closest.last
    end

  end

  def next
    self.class.greater_date(date).valid_date.non_performed.closest.first
  end

  def previous
    self.class.less_date(date).valid_date.non_performed.closest.last
  end

  def countdown
    now = DateTime.now
    diff = now.difference_in_days_hours_mins(date)
    '%.2d days, %.2d hours, %.2d minutes' % [diff.days, diff.hours , diff.minutes]
  end

  def musician_has_more_than_one_non_performed_concert
    if musician_profile.concerts.non_performed.size > 1
      errors.add(:performed, ": Musician can't have more than one concert non performed")
    end
  end




  def genres
    challenge.genres_list
  end

  private
  def date_is_less_than_now
    if date < DateTime.now
      errors.add(:date, "can't be less than now")
    end
  end


end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_filter :authenticate_user!, except: :show
  before_filter :validate_musician!, except: :show
  def new
    @concert = Concert.new
    @concert.challenge_id = params[:challenge] 
  end

  def destroy

    @concert = Concert.find(params[:id])
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Concert canceled!' }
      format.json { head :no_content }
    end
  end

  def create
    @concert = current_user.musician_profile.concerts.new params[:concert]
    if @concert.save
      redirect_to musician_profile_path(current_user.musician_profile), notice: "Concert created" 
    else
      render :new
    end
  end

  def show
    @concert = Concert.includes(:musician_profile => [:fans]).find(params[:id])
    if user_signed_in?
      @ticket = Ticket.new(user_id: current_user.id, concert_id: @concert.id)
      @musician_profile = @concert.musician
      @user_musician_profile = current_user.musician_profile
      @tip = Tip.new(musician_profile_id: @musician_profile.id, user_id: current_user.id)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def validate_musician!
    musician_profile = current_user.musician_profile
    unless musician_profile.valid_profile?
      flash[:error] = 'Your musician profile is not valid or hasn\'t been validated yet'
      redirect_to musician_profile_path(musician_profile)
    end  
  end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
  def on_air_path(concert)
    if concert
      concert_path(concert)
    else
      nil
    end
  end

  def buy_ticket_path(concert)
    if user_signed_in?
      new_concert_ticket_path(concert)
    else
      '#log-in-modal'
    end
  end
end

app/views/concerts/_concert_description.html.erb
<div class="span7 draw-border">
  <div id ="concert-description" class="row-fluid">
    <div class="span3">
      <ul class="thumbnails">
        <li class="span12">
          <% if @concert.musician_profile.photo? %>
            <%= image_tag @concert.musician_profile.photo_url %>
          <% else %>
            <img data-src="holder.js/200x200" alt="">
          <% end %>
        </li>
      </ul>
    </div>
    <div class="span9 subpattern1">
      <div class="row-fluid">
        DATE: <%= @concert.pretty_date %>
      </div>
      <div class="row-fluid">
        COUNTDOWN: <%= @concert.countdown %>
      </div>
      <div class="row-fluid">
        COVER NAME: <%= @concert.challenge.song_name %> / <%= @concert.challenge.artist_name %>
      </div>
      <div class="row-fluid">
        Musician NAME: <%= link_to @concert.musician, musician_profile_path(@concert.musician) %>
      </div>
      <div class="row-fluid">
        DURATION: <%= pluralize(@concert.duration, 'minute') %>
      </div>
      <div class="row-fluid">
        <%= @concert.description %>
      </div>
    </div>
  </div>

  <div class="row-fluid buy-wrapper">
    <div class="span9 offset3">
      <% if user_signed_in? && !current_user.has_ticket?(@concert) %>
        <%= link_to 'BUY TICKET', '#buy-ticket-modal', data: {toggle: 'modal'}, :class => 'btn btn-buy-ticket' %>
        <%= render @ticket %>
      <% elsif !user_signed_in? %>
        <%= link_to 'BUY TICKET', '#log-in-modal', data: {toggle: 'modal', link_to: root_path}, :class => 'btn btn-buy-ticket sign-in-required' %>
      <% end %>
    </div>
  </div>

  <div class="row-fluid play-wrapper">
    <%= link_to show_concert_broadcast_path(@concert), data: {toggle: 'modal', link_to: root_path}, class: 'sign-in-required', remote: true do %>
      <div class="span9 offset3">
        <div class="arrow-right"></div>
        PLAY
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <%= render @tip %>
  <% end %>
  <div class="row-fluid">
    <%= link_to give_tip_path(@concert.musician_profile), data: {toggle: 'modal', link_to: root_path}, class: 'sign-in-required' do %>
      <div class="give-tip">
        TIP this Musician
      </div>
    <% end %>
  </div>

</div>

app/views/concerts/_show.html.erb
<div class="center-online">
  <div class="first-line">WATCH</div>
  <div class="second-line">LIVE ONLINE CONCERTS</div>
  <div class="third-line">ON AIR</div>
</div>

<% if @concert %>
  <%= div_for @concert, class: "row" do %>
    <%= render 'concerts/concert_description' %>
    <div class="span4 draw-border pattern4">
      <div class="row-fluid subpattern4">
        FANS LIST
      </div>
      <br/>
      <% @concert.musician_profile.fans.each do |fan| %>
      <div class="row-fluid">
        <%= fan.name %>
      </div>
      <% end %>
    </div>
  <% end %>

  <%= link_to on_air_path(@concert.previous), remote: true, id: 'previous_concert' do %>
    <div class="previous-wrapper">
      <div class="previous left-arrow orange-arrow">
      </div>
    </div>  
  <% end if @concert.previous %>

  <%= link_to on_air_path(@concert.next), remote: true, id: 'next_concert' do %>
    <div class="next-wrapper">
      <div class="next right-arrow orange-arrow">
      </div>
    </div>
  <% end if @concert.next %>
<% end %>

app/views/concerts/new.html.erb
<%= form_for(@concert) do |f| %>
  <% @concert.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  <%= f.hidden_field :challenge_id %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    Duration in minutes:
    <div class="control-group form-inline">
    <%= f.radio_button(:duration, '10') %>
    <%= f.label(:duration, '10') %>
    <%= f.radio_button(:duration, '30') %>
    <%= f.label(:duration, '30') %>
    </div>
  </div>
  <div>
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>
  <%= f.button 'Create', type: :submit, :class => "btn btn-rmys" %>
<% end %>

app/views/concerts/show.html.erb
<% content_for :onair_nav do %>
  chosen_nav
<% end %>

<div id="show-concert">
  <%= render 'show' %>
</div>

app/views/concerts/show.js.erb
$('#show-concert').html("<%= escape_javascript render('show') %>");